version: '3.9'

services:
  backend:
    container_name: fastgpt2
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0"
